import { Look } from './types';

export const LAUNCH_LOOKS: Look[] = [
  {
    id: 'look-1',
    slug: 'the-sovereign',
    name: 'THE SOVEREIGN',
    subName: 'Look 01 — Flagship Power',
    occasion: 'Boardroom, Private Gallery Opening, Diplomatic Reception',
    paletteDescription: 'Ivory + Near-Black with Subtle Bone Patina',
    paletteColors: ['#F5EFE4', '#1A1611', '#E8E0D5', '#3D352B'],
    statementQuote: 'The room notices before you speak.',
    longThesis:
      'A study in quiet dominance. The silhouette trades aggressive angularity for relaxed, heavyweight draping. The oversized double-pleated trouser grounds the posture, while the hand-finished silk-cotton tunic shirt softens the neckline.',
    tier: 'EDIT',
    season: 'Season I: The Inaugural Wardrobe',
    seasonCode: 'SEASON_I',
    status: 'active',
    allocationNotes: 'Active Curation · 4 complete ensemble allocations remaining this month',
    oneRuleBroken:
      'Precision chest tailoring contrasted against an exaggerated, wide-sweep fluid hem.',
    heroImage:
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
        caption: 'Full Silhouette — Natural morning light in quiet terrazzo gallery',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — 380gsm dry wool-linen weave drape',
        type: 'texture',
      },
      {
        url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Detail Context — Minimalist obsidian dial and signet edge',
        type: 'accessory',
      },
      {
        url: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Second Angle — Mid-stride with natural shoulder structure',
        type: 'second_angle',
      },
    ],
    items: [
      {
        id: 'sov-01',
        name: 'Silk-Cotton Pleated Tunic Shirt',
        category: 'Shirt',
        price: 340,
        currency: 'USD',
        composition: '70% Muga Silk, 30% Long-Staple Egyptian Cotton (210gsm)',
        tier: 'EDIT',
        origin: 'Porto / Northern Portugal Atelier',
        silhouette: 'Relaxed body with structured French placket and drop shoulder',
        image:
          'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Cut generously through the body to create fluid movement when in motion. Finished with concealed mother-of-pearl buttons and soft band collar.',
        curationNote:
          'Selected by METAMORPHOO. Curated to standard. Natural drape eliminates any synthetic tension.',
        fitGuidance: {
          cut: 'Fluid Architectural',
          modelStats: 'Model is 187cm / 6\'1.5", 76kg, wearing Size L for natural drop',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Select your usual size. Designed with 6cm generous chest clearance.',
          measurementsSummary: {
            chestOrWaist: '118cm (Size L Chest)',
            length: '78cm Body Length',
            hemOrOpening: 'Straight vented hem',
          },
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 32 },
      },
      {
        id: 'sov-02',
        name: 'Wide-Leg High-Waist Wool Trousers',
        category: 'Trousers',
        price: 460,
        currency: 'USD',
        composition: '85% Tropical Virgin Wool, 15% Mulberry Silk (340gsm)',
        tier: 'EDIT',
        origin: 'Biella Mill, Northern Italy',
        silhouette: 'Deep double forward pleats, 24cm hem opening, side adjusters',
        image:
          'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=800&q=85',
        sizes: ['46 (30)', '48 (32)', '50 (34)', '52 (36)'],
        description:
          'Constructed without belt loops for an uninterrupted architectural waistline. Heavyweight drape breaks cleanly over the shoe.',
        curationNote:
          'Selected by METAMORPHOO. Curated to standard. The baggy proportion is disciplined and intentional.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Model is 187cm, waist 31", wearing Size 48 with side tabs engaged',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'Order by true natural waist. The leg is cut intentionally wide (24cm hem).',
          measurementsSummary: {
            chestOrWaist: '84cm Waist (Size 48)',
            length: '108cm Outseam with 5cm turn-up reserve',
            hemOrOpening: '24cm Leg Opening',
          },
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 64 },
      },
      {
        id: 'sov-03',
        name: 'Hand-Burnished Calfskin Loafers',
        category: 'Shoes',
        price: 520,
        currency: 'USD',
        composition: 'Full-Grain Box Calf Leather, Vegetable-Tanned Leather Sole',
        tier: 'EDIT',
        origin: 'Almansa, Spain',
        silhouette: 'Slightly elongated almond toe with Goodyear-welted channeled sole',
        image:
          'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=85',
        sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
        description:
          'Hand-patinated to a deep espresso tone that catches amber highlights in low ambient light. Memory foam-cushioned insole.',
        curationNote:
          'Selected by METAMORPHOO. Curated to standard. Soft break-in with museum-grade leather luster.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Fits true to European dress shoe sizing',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'True to European dress sizing. For half sizes, take the next size down.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 52, y: 92 },
      },
      {
        id: 'sov-04',
        name: 'Minimalist Obsidian Dial Dress Watch',
        category: 'Watch',
        price: 680,
        currency: 'USD',
        composition: '38mm Brushed Stainless Steel, Black Onyx Dial, Alligator-Embossed Calf Strap',
        tier: 'EDIT',
        origin: 'Geneva / Bespoke Horology Partner',
        silhouette: 'Ultra-thin 6.8mm case profile with two-hand minimalist layout',
        image:
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=85',
        sizes: ['One Size (38mm)'],
        description:
          'Deconstructs the watch into pure form: no numerals, no logo on the face, only two rhodium-plated leaf hands gliding over polished natural obsidian.',
        curationNote:
          'Selected by METAMORPHOO. Curated to standard. Unbranded dial upholds the quiet luxury doctrine.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: '38mm diameter sits elegantly on wrists from 15cm to 21cm circumference',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Universal sizing with 7 pre-punched strap adjustments',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 38, y: 48 },
      },
      {
        id: 'sov-05',
        name: 'Vetiver & Smoked Bergamot Extract',
        category: 'Fragrance',
        price: 210,
        currency: 'USD',
        composition: 'Extrait de Parfum (30% Oil Concentration) — 50ml',
        tier: 'EDIT',
        origin: 'Grasse, France',
        silhouette: 'Smoked Haitian vetiver, Calabrian bergamot, Spanish cistus labdanum',
        image:
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=85',
        sizes: ['50ml Extrait'],
        description:
          'Opens with crisp citrus before settling into an earthy, aristocratic resin that stays within a 2-foot aura.',
        curationNote:
          'Selected by METAMORPHOO. Curated to standard. Never sweet; clean dry woods.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Concentrated formulation: 2-3 sprays provide 10-hour personal sillage',
          drapeWeight: 'Lightweight (180gsm)',
          recommendedSizing: '50ml flacon in heavy smoked glass with magnetic cap',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 62, y: 44 },
      },
    ],
  },
  {
    id: 'look-2',
    slug: 'the-nocturne',
    name: 'THE NOCTURNE',
    subName: 'Look 02 — Evening Intimacy',
    occasion: 'Intimate Dinner, Midnight Salon, Private Collector Event',
    paletteDescription: 'Near-Black + Deep Charcoal with Burnt Sienna Accents',
    paletteColors: ['#1A1611', '#2A241E', '#C4623A', '#E8E0D5'],
    statementQuote: 'Composure in low light.',
    longThesis:
      'Engineered for spaces with dim candlelight and heavy velvet curtains. The midnight-charcoal open collar breathes without collapsing, paired with unpressed pleated linen trousers.',
    tier: 'EDIT',
    season: 'Season I: The Inaugural Wardrobe',
    seasonCode: 'SEASON_I',
    status: 'active',
    allocationNotes: 'Active Curation · 3 complete ensemble allocations available',
    oneRuleBroken:
      'Formal dark evening palette subverted with an unbuttoned relaxed camp-collar shirt.',
    heroImage:
      'https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?auto=format&fit=crop&w=1200&q=85',
        caption: 'Full Silhouette — Twilight ambiance against weathered limestone',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — Textured raw mulberry silk matte surface',
        type: 'texture',
      },
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
        caption: 'Accessory Context — Hand-carved carnelian ring on oxidized silver',
        type: 'accessory',
      },
    ],
    items: [
      {
        id: 'noc-01',
        name: 'Matte Raw Silk Midnight Camp Shirt',
        category: 'Shirt',
        price: 380,
        currency: 'USD',
        composition: '100% Noil Raw Mulberry Silk (240gsm)',
        tier: 'EDIT',
        origin: 'Como / Lombardy, Italy',
        silhouette: 'Relaxed boxy body with open Cuban rever collar and dropped hem',
        image:
          'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Matte, dry hand-feel that absorbs ambient light rather than reflecting it. Cut straight at the waist for effortless untucked wear.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Zero synthetic sheen.',
        fitGuidance: {
          cut: 'Fluid Architectural',
          modelStats: 'Model is 185cm, wearing Size M for clean relaxed drop',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to size for relaxed fit. Cut straight through waist.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 30 },
      },
      {
        id: 'noc-02',
        name: 'Single-Pleat Heavy Charcoal Linen Trousers',
        category: 'Trousers',
        price: 420,
        currency: 'USD',
        composition: '100% Heavyweight Normandy Flamed Linen (380gsm)',
        tier: 'EDIT',
        origin: 'Guimarães, Portugal',
        silhouette: 'Single deep inward pleat, high rise, gentle taper to 22cm opening',
        image:
          'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=85',
        sizes: ['46 (30)', '48 (32)', '50 (34)', '52 (36)'],
        description:
          'Substantial 380gsm linen that drapes like wool while retaining the breathable, organic character of pure flax. Deep charcoal hue with slate undertones.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Heavyweight flax drape.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Model is 185cm, wearing Size 48',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'True to waist size. Generous thigh room with elegant break.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 65 },
      },
      {
        id: 'noc-03',
        name: 'Woven Leather Venetian Slippers',
        category: 'Shoes',
        price: 490,
        currency: 'USD',
        composition: 'Hand-Intrecciato Calf Leather, Cuoio Hard Leather Sole',
        tier: 'EDIT',
        origin: 'Riviera del Brenta, Italy',
        silhouette: 'Low-profile slip-on with soft heel counter (can be worn collapsed)',
        image:
          'https://images.unsplash.com/photo-1533867617858-e7b97e060509?auto=format&fit=crop&w=800&q=85',
        sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
        description:
          'Soft calf strips hand-braided on a vintage wooden last. The supple heel can be stepped on for an informal mule silhouette.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Fits standard EU shoe size; leather molds to foot after two wears',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to European size.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 52, y: 92 },
      },
      {
        id: 'noc-04',
        name: 'Oxidized Silver Carnelian Signet Ring',
        category: 'Accessory',
        price: 310,
        currency: 'USD',
        composition: 'Solid 925 Sterling Silver with Matte Sulfur Oxidation, Natural Madagascan Carnelian',
        tier: 'EDIT',
        origin: 'Lagos / Master Goldsmith Guild',
        silhouette: 'Cushion-cut cabochon stone set in heavy textured bezel',
        image:
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85',
        sizes: ['US 8', 'US 9', 'US 10', 'US 11'],
        description:
          'Deep burnt-orange carnelian stone acts as the single warm ember puncturing the midnight ensemble.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. West African artisan metalwork.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Worn on pinky or ring finger',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Select ring finger or pinky sizing according to preference.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 35, y: 52 },
      },
      {
        id: 'noc-05',
        name: 'Tobacco Flower & Amber Resin Attar',
        category: 'Fragrance',
        price: 240,
        currency: 'USD',
        composition: 'Pure Concentrated Perfume Oil — 15ml Crystal Flacon with Glass Wand',
        tier: 'EDIT',
        origin: 'Marrakech / Heritage Distiller',
        silhouette: 'Night-blooming tobacco flower, warm ambergris resin, roasted tonka bean',
        image:
          'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=85',
        sizes: ['15ml Attar'],
        description:
          'An oil-based ritual applied directly to pulse points. Intimate, smoldering warmth that only surfaces upon close physical proximity.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Pure perfume oil: single wand touch lasts 14+ hours',
          drapeWeight: 'Lightweight (180gsm)',
          recommendedSizing: '15ml heavy crystal applicator',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 65, y: 42 },
      },
    ],
  },
  {
    id: 'look-3',
    slug: 'the-heir',
    name: 'THE HEIR',
    subName: 'Look 03 — Relaxed Lineage',
    occasion: 'Sunday Terrace Salon, Estate Garden Walk, Coastal Architecture Tour',
    paletteDescription: 'Warm Cream + Stone Olive with Aged Brass Accents',
    paletteColors: ['#EFECE6', '#545848', '#C9B89A', '#1A1611'],
    statementQuote: 'Ease that comes from time, not effort.',
    longThesis:
      'The look of someone whose grandfather built the villa. Soft unbleached knitwear layered over stone-washed olive trousers. Generous volumes suggest comfort without sloppiness.',
    tier: 'EDIT',
    season: 'Season I: The Inaugural Wardrobe',
    seasonCode: 'SEASON_I',
    status: 'active',
    allocationNotes: 'Active Curation · 5 complete ensemble allocations available',
    oneRuleBroken:
      'Prestige tailored trousers paired with an ultra-chunky open-gauge fisherman stitch sweater.',
    heroImage:
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=85',
        caption: 'Full Silhouette — Natural golden hour on sunlit terrace stairs',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — Heavy gauge untreated cotton-linen waffle rib',
        type: 'texture',
      },
      {
        url: 'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=1200&q=85',
        caption: 'Accessory Context — Beveled Japanese bio-acetate amber frame',
        type: 'accessory',
      },
    ],
    items: [
      {
        id: 'heir-01',
        name: 'Open-Gauge Cotton-Linen Knit Polo',
        category: 'Knitwear',
        price: 360,
        currency: 'USD',
        composition: '55% Organic Seed Cotton, 45% Raw Belgian Linen (320gsm)',
        tier: 'EDIT',
        origin: 'Perugia, Umbria, Italy',
        silhouette: 'Placketless Johnny collar with dropped shoulder and relaxed rib hem',
        image:
          'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Knitted on 7-gauge machines with deliberate slight irregularity in the yarn slub. Sits comfortably against bare skin in warm sea breezes.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Breathable open-stitch.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Model is 188cm, wearing Size L for generous sleeve length',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to size. Has natural knit stretch.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 30 },
      },
      {
        id: 'heir-02',
        name: 'Stone-Washed Olive Double-Pleated Trousers',
        category: 'Trousers',
        price: 410,
        currency: 'USD',
        composition: '100% Long-Staple Cotton Twill with Enzyme Wash (360gsm)',
        tier: 'EDIT',
        origin: 'Kojima, Okayama, Japan',
        silhouette: 'Deep double forward pleats with wide barrel leg and 4cm cuffs',
        image:
          'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=85',
        sizes: ['46 (30)', '48 (32)', '50 (34)', '52 (36)'],
        description:
          'Muted olive pigment dye faded through artisan enzyme baths to mimic twenty years of terrace sun exposure.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Heavyweight Japanese cotton.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Model is 188cm, wearing Size 50',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'True to size with generous volume through thigh and knee.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 65 },
      },
      {
        id: 'heir-03',
        name: 'Unlined Suede Penny Loafers',
        category: 'Shoes',
        price: 480,
        currency: 'USD',
        composition: 'Reverse Calf Suede (Sand Tone), Flexible Blake Stitching, Single Leather Sole',
        tier: 'EDIT',
        origin: 'Florence / Tuscany, Italy',
        silhouette: 'Soft unconstructed penny loafer with round moc-stitched toe',
        image:
          'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=85',
        sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
        description:
          'Zero stiffeners in the heel or toe box: fits like a glove from the first hour. Sandstone shade complements muted linen tones.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Standard EU sizing; unlined leather yields gently to foot width',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to European size.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 52, y: 92 },
      },
      {
        id: 'heir-04',
        name: 'Amber Bio-Acetate Square Sunglasses',
        category: 'Eyewear',
        price: 340,
        currency: 'USD',
        composition: '8mm Cured Plant-Based Acetate, Mineral Green Glass Lenses (100% UV Protection)',
        tier: 'EDIT',
        origin: 'Sabae / Fukui Prefecture, Japan',
        silhouette: 'Bold geometric silhouette with custom 7-barrel custom wire-core hinges',
        image:
          'https://images.unsplash.com/photo-1508296695146-257a814070b4?auto=format&fit=crop&w=800&q=85',
        sizes: ['One Size (49-21-145)'],
        description:
          'Substantial 8mm acetate profile with beveled temple edges that catch directional sunlight.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Hand-polished in Sabae.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Medium-wide bridge fit suitable for medium to wide face profiles',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Universal sizing with adjustable core-wire temples.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 15 },
      },
      {
        id: 'heir-05',
        name: 'Neroli & Moroccan Cedar Eau de Parfum',
        category: 'Fragrance',
        price: 220,
        currency: 'USD',
        composition: 'Eau de Parfum (22% Concentration) — 50ml Solid Flacon',
        tier: 'EDIT',
        origin: 'Seville / Grasse',
        silhouette: 'Orange Blossom, Bitter Petitgrain, Moroccan Cedarwood',
        image:
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=85',
        sizes: ['50ml EDP'],
        description:
          'Evokes afternoon sun beating down on ancient cedar beams and flowering citrus trees.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Light, radiant projection ideal for open-air terraces',
          drapeWeight: 'Lightweight (180gsm)',
          recommendedSizing: '50ml flacon',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 65, y: 40 },
      },
    ],
  },
  {
    id: 'look-4',
    slug: 'the-attache',
    name: 'THE ATTACHE',
    subName: 'Look 04 — Modern Diplomat',
    occasion: 'International Summit, Cross-Border Signing, High Commission Meeting',
    paletteDescription: 'Mid-Grey Slate + Crisp Bone with Warm Saddle Leather',
    paletteColors: ['#6B7280', '#F5EFE4', '#8C5E3C', '#1A1611'],
    statementQuote: 'Precision without tension.',
    longThesis:
      'The traditional diplomatic uniform stripped of bureaucratic stuffiness. A unlined tropical wool overshirt worn closed over wide tailored flannel trousers.',
    tier: 'EDIT',
    season: 'Season I: The Inaugural Wardrobe',
    seasonCode: 'SEASON_I',
    status: 'low_stock',
    allocationNotes: 'Final Season Allocations · 2 complete sets remaining',
    oneRuleBroken:
      'Formal high-commission setting met with an unlined chore jacket silhouette in place of a stiff blazer.',
    heroImage:
      'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Full Silhouette — Architectural stone colonnade in sharp afternoon light',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — 300gsm slate tropical wool micro-twill',
        type: 'texture',
      },
      {
        url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=85',
        caption: 'Accessory Context — Saddle tan bridle leather diplomat portfolio',
        type: 'accessory',
      },
    ],
    items: [
      {
        id: 'att-01',
        name: 'Structured Bone Poplin Dress Shirt',
        category: 'Shirt',
        price: 310,
        currency: 'USD',
        composition: '100% Giza 87 Egyptian Cotton Poplin (180gsm)',
        tier: 'EDIT',
        origin: 'Milan, Italy',
        silhouette: 'Semi-spread semi-fused collar, clean French front',
        image:
          'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Crisp bone hue rather than stark optical white. Retains sharp collar roll without constriction.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Model is 186cm, wearing Size M for crisp shoulder seam placement',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to collar and neck measurement.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 30 },
      },
      {
        id: 'att-02',
        name: 'Mid-Grey Slate Wool Overshirt',
        category: 'Jacket',
        price: 520,
        currency: 'USD',
        composition: '100% Super 130s Wool Flannel (300gsm)',
        tier: 'EDIT',
        origin: 'Huddersfield / Yorkshire, UK',
        silhouette: 'Straight square hem, two flush breast pockets, genuine horn buttons',
        image:
          'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Substitutes the stiff blazer with a clean architectural wool jacket that moves without noise.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Yorkshire milled wool.',
        fitGuidance: {
          cut: 'Fluid Architectural',
          modelStats: 'Model is 186cm, wearing Size L for layering over shirt',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Select your normal jacket size.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 38 },
      },
      {
        id: 'att-03',
        name: 'Charcoal Double-Pleated Flannel Trousers',
        category: 'Trousers',
        price: 440,
        currency: 'USD',
        composition: '90% Wool, 10% Cashmere (350gsm)',
        tier: 'EDIT',
        origin: 'Biella, Italy',
        silhouette: 'Extended waistband tab with horn closure, deep pleats, 23cm hem',
        image:
          'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=85',
        sizes: ['46 (30)', '48 (32)', '50 (34)', '52 (36)'],
        description:
          'Cashmere-blend softness with heavy architectural fall. Retains sharp center crease throughout long international flights.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Model is 186cm, wearing Size 48',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'Order by true waist measurement.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 68 },
      },
      {
        id: 'att-04',
        name: 'Bridle Leather Document Folio',
        category: 'Accessory',
        price: 460,
        currency: 'USD',
        composition: 'English Bridle Leather, Suede Lining, Solid Brass Zipper',
        tier: 'EDIT',
        origin: 'Walsall, UK',
        silhouette: 'Slim envelope profile designed for A4 correspondence and 14" laptop',
        image:
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=800&q=85',
        sizes: ['One Size (36 x 26 cm)'],
        description:
          'Waxes and oils tallow-dressed into the grain for rich self-healing patina with age.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Heritage saddle leather.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Holds 14" MacBook and paper archives with zero bulk',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'One size',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 30, y: 60 },
      },
      {
        id: 'att-05',
        name: 'Black Tea & Cardamom Cologne Concentrée',
        category: 'Fragrance',
        price: 215,
        currency: 'USD',
        composition: 'Cologne Concentrée (20% Concentration) — 100ml',
        tier: 'EDIT',
        origin: 'London / Grasse',
        silhouette: 'Ceylon Black Tea leaves, Green Cardamom Pods, Cedar Bark',
        image:
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=85',
        sizes: ['100ml EDC'],
        description:
          'Dry, intellectual fragrance with zero sweetness. Imparts authority and calm concentration.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Dry, crisp projection suited for closed diplomatic meeting rooms',
          drapeWeight: 'Lightweight (180gsm)',
          recommendedSizing: '100ml flacon',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 65, y: 44 },
      },
    ],
  },
  {
    id: 'look-5',
    slug: 'the-meridian',
    name: 'THE MERIDIAN',
    subName: 'Look 05 — Equatorial Breeze',
    occasion: 'Island Harbor Luncheon, Architectural Biennale, Private Yacht Transfer',
    paletteDescription: 'Raw Sand + Sun-bleached Linen with Malachite Green Accent',
    paletteColors: ['#D6C7B2', '#E8E0D5', '#245C4F', '#1A1611'],
    statementQuote: 'Elegance built for heat.',
    longThesis:
      'Engineered for the humid warmth of Lagos lagoons and Mediterranean harbors. Cut in loose, unbleached linen with a wide fluid hem that catches every ambient breeze.',
    tier: 'EDIT',
    season: 'Season I: The Inaugural Wardrobe',
    seasonCode: 'SEASON_I',
    status: 'active',
    allocationNotes: 'Active Curation · 4 complete ensemble allocations available',
    oneRuleBroken:
      'Lightweight resort linen silhouette grounded with a raw emerald-toned African malachite cuff.',
    heroImage:
      'https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1488161628813-04466f872be2?auto=format&fit=crop&w=1200&q=85',
        caption: 'Full Silhouette — Glare off water on stone wharf at midday',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — 260gsm raw unbleached Irish linen weave slub',
        type: 'texture',
      },
      {
        url: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=1200&q=85',
        caption: 'Accessory — Raw African malachite cuff with hand-chiseled silver finials',
        type: 'accessory',
      },
    ],
    items: [
      {
        id: 'mer-01',
        name: 'Sand Unbleached Linen Safari Overshirt',
        category: 'Shirt',
        price: 360,
        currency: 'USD',
        composition: '100% Unbleached Flamed Flax Linen (260gsm)',
        tier: 'EDIT',
        origin: 'Ballymena, Northern Ireland',
        silhouette: 'Four bellows pockets, convertible notch collar, side-vented hem',
        image:
          'https://images.unsplash.com/photo-1584273143981-41c073dfe8f8?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Untreated, dye-free flax containing natural seed flecks. Thick yarn allows air circulation through the weave.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Zero synthetic dyes.',
        fitGuidance: {
          cut: 'Fluid Architectural',
          modelStats: 'Model is 187cm, wearing Size L for generous ventilation',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to size with spacious body cut.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 32 },
      },
      {
        id: 'mer-02',
        name: 'Wide-Leg Cream Linen Trousers',
        category: 'Trousers',
        price: 390,
        currency: 'USD',
        composition: '100% Pure Normandy Linen (320gsm)',
        tier: 'EDIT',
        origin: 'Porto, Portugal',
        silhouette: 'Continuous waistband, deep double reverse pleats, 25cm hem width',
        image:
          'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=800&q=85',
        sizes: ['46 (30)', '48 (32)', '50 (34)', '52 (36)'],
        description:
          'Dense 320gsm linen weight prevents see-through translucency while creating majestic stacking over leather slides.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Non-sheer linen.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Model is 187cm, wearing Size 48',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'True to waist size. Extra wide 25cm hem line.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 65 },
      },
      {
        id: 'mer-03',
        name: 'Cross-Strap Raw Leather Harbor Slides',
        category: 'Shoes',
        price: 340,
        currency: 'USD',
        composition: '4mm Vegetable-Tanned Saddle Leather, Hand-Beveled Edge, Stacked Leather Heel',
        tier: 'EDIT',
        origin: 'Capri, Italy',
        silhouette: 'Wide criss-cross vamp straps on anatomical leather footbed',
        image:
          'https://images.unsplash.com/photo-1560769629-975ec94e6a86?auto=format&fit=crop&w=800&q=85',
        sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
        description:
          'Constructed from thick saddle leather that darkens into a rich golden amber with wear and sun exposure.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Fits standard EU sizing',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to European size.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 52, y: 92 },
      },
      {
        id: 'mer-04',
        name: 'Raw Malachite & Silver Cable Cuff',
        category: 'Accessory',
        price: 390,
        currency: 'USD',
        composition: 'Solid 925 Sterling Silver, Natural Banded Congolese Malachite Spheres',
        tier: 'EDIT',
        origin: 'Lagos, Nigeria',
        silhouette: 'Flexible wire cable cuff with emerald-veined malachite spheres',
        image:
          'https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=85',
        sizes: ['M (17-19cm)', 'L (19-21cm)'],
        description:
          'Vivid banded green malachite brings natural geological contrast to the neutral linen tones.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Handcrafted in Lagos.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Size M fits most wrists; pliable tension allows custom contouring',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Select M for under 19cm wrist, L for over 19cm.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 35, y: 52 },
      },
      {
        id: 'mer-05',
        name: 'Crushed Fig Leaf & Sea Salt Botanical Water',
        category: 'Fragrance',
        price: 195,
        currency: 'USD',
        composition: 'Eau de Cologne — 100ml Heavy Amber Glass with Splash Stopper',
        tier: 'EDIT',
        origin: 'Marseille, France',
        silhouette: 'Crushed Wild Fig Leaf, Marine Salt, Sunlit Driftwood',
        image:
          'https://images.unsplash.com/photo-1547887537-6158d64c35b3?auto=format&fit=crop&w=800&q=85',
        sizes: ['100ml EDC'],
        description:
          'Crisp, green sap and salty spray that invigorates without overpowering intimate conversation.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'Refreshing splash cologne formulation for hot humid climates',
          drapeWeight: 'Lightweight (180gsm)',
          recommendedSizing: '100ml splash flacon',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 65, y: 40 },
      },
    ],
  },
  {
    id: 'look-6',
    slug: 'the-consul',
    name: 'THE CONSUL',
    subName: 'Look 06 — Ceremonial Minimalist',
    occasion: 'State Banquet, Opera Gala Opening, Embassy Salon',
    paletteDescription: 'Deep Midnight Blue + Black with Gold Threading',
    paletteColors: ['#0E1B2A', '#1A1611', '#C9B89A', '#E8E0D5'],
    statementQuote: 'Ceremony without stiffness.',
    longThesis:
      'A deconstruction of evening formalwear. Replaces the rigid cummerbund and synthetic bowtie with a clean standing collar tunic and sweeping fluid trousers.',
    tier: 'EDIT',
    season: 'Season I: The Inaugural Wardrobe',
    seasonCode: 'SEASON_I',
    status: 'active',
    allocationNotes: 'Active Curation · 3 complete ensemble allocations available',
    oneRuleBroken:
      'Strict black-tie protocol subverted by pairing a midnight wool tunic with fluid bone trousers.',
    heroImage:
      'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=1200&q=85',
        caption: 'Full Silhouette — Grand marble stairway under warm sconce chandeliers',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — Deep midnight barathea wool weave with matte grain',
        type: 'texture',
      },
      {
        url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=85',
        caption: 'Detail Context — Vintage gold guilloché 36mm dress watch',
        type: 'accessory',
      },
    ],
    items: [
      {
        id: 'con-01',
        name: 'Midnight Barathea Silk-Lined Tunic',
        category: 'Jacket',
        price: 680,
        currency: 'USD',
        composition: '100% Super 150s Barathea Wool, Silk Habotai Lining (320gsm)',
        tier: 'EDIT',
        origin: 'London / Savile Row Collaboration',
        silhouette: 'Standing mandarin collar, concealed hand-sewn frogging closure',
        image:
          'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=85',
        sizes: ['S', 'M', 'L', 'XL'],
        description:
          'Combines West African ceremonial tunic structure with British black-tie barathea wool for unrivaled gala presence.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard. Ceremonial barathea.',
        fitGuidance: {
          cut: 'Fluid Architectural',
          modelStats: 'Model is 189cm, wearing Size L for regal shoulder drape',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'True to chest size.',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 35 },
      },
      {
        id: 'con-02',
        name: 'Bone White Fluid Pleated Trousers',
        category: 'Trousers',
        price: 450,
        currency: 'USD',
        composition: '70% Wool, 30% Silk Crepe (320gsm)',
        tier: 'EDIT',
        origin: 'Biella, Italy',
        silhouette: 'Twin deep reverse pleats, 25cm generous hem line',
        image:
          'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=800&q=85',
        sizes: ['46 (30)', '48 (32)', '50 (34)', '52 (36)'],
        description:
          'The deliberate rule-breaker: pairing bone fluid trousers with midnight black-tie creates unforgettable contrast.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Model is 189cm, wearing Size 50',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'True to waist size.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 68 },
      },
      {
        id: 'con-03',
        name: 'Handmade Patent Leather Opera Pumps',
        category: 'Shoes',
        price: 580,
        currency: 'USD',
        composition: 'Mirrored Patent Calfskin, Grosgrain Flat Bow, Red Leather Lining',
        tier: 'EDIT',
        origin: 'Montegranaro, Italy',
        silhouette: 'Low-cut vamp with hand-stitched grosgrain evening ribbon',
        image:
          'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=85',
        sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
        description:
          'Classic black-tie footwear refined with a contemporary softened toe curve for effortless dignity.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Fits true to European gala shoe sizing',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'True to European size.',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 52, y: 92 },
      },
      {
        id: 'con-04',
        name: 'Vintage Guilloché Gold Dress Watch',
        category: 'Watch',
        price: 890,
        currency: 'USD',
        composition: '18k Yellow Gold Plated 36mm Case, Hand-Turned Silver Guilloché Dial',
        tier: 'EDIT',
        origin: 'La Chaux-de-Fonds, Switzerland',
        silhouette: 'Ultra-thin manual mechanical winding movement with Breguet numerals',
        image:
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=85',
        sizes: ['One Size (36mm)'],
        description:
          'The 36mm proportion honors traditional gala codes. Guilloché dial radiates light under chandelier chandeliers.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Structured Tailored',
          modelStats: 'Classic 36mm gala dress proportion',
          drapeWeight: 'Medium Drape (240-300gsm)',
          recommendedSizing: 'Universal sizing with genuine crocodile grain strap',
        },
        provenance: {
          condition: 'Atelier Curated Standard',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 38, y: 50 },
      },
      {
        id: 'con-05',
        name: 'Santal & Oud Imperial Absolu',
        category: 'Fragrance',
        price: 280,
        currency: 'USD',
        composition: 'Extrait de Parfum (35% Oil Concentration) — 50ml Solid Crystal Bottle',
        tier: 'EDIT',
        origin: 'Grasse, France',
        silhouette: 'Mysore Sandalwood, Aged Assam Agarwood, Taif Rose, Myrrh',
        image:
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=85',
        sizes: ['50ml Extrait'],
        description:
          'Rich, creamy aged sandalwood layered over aristocratic dark resins. Royal without being ostentatious.',
        curationNote: 'Selected by METAMORPHOO. Curated to standard.',
        fitGuidance: {
          cut: 'Natural Drop',
          modelStats: 'High-concentration resin: single drop on collar lasts 24 hours',
          drapeWeight: 'Lightweight (180gsm)',
          recommendedSizing: '50ml crystal flacon',
        },
        provenance: {
          condition: 'Brand New / Pristine Deadstock',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 62, y: 44 },
      },
    ],
  },
];

export const ARCHIVE_VAULT_LOOKS: Look[] = [
  {
    id: 'vault-1',
    slug: 'the-viceroy',
    name: 'THE VICEROY',
    subName: 'Season 0 Archive · Look 01 (Vaulted)',
    occasion: 'Archival Study, Private Commission Historical Record',
    paletteDescription: 'Raw Camel + Tobacco Slate',
    paletteColors: ['#A57C52', '#3D352B', '#E8E0D5', '#1A1611'],
    statementQuote: 'The weight of unyielding heritage.',
    longThesis:
      'Archived from the private inaugural salon in Lisbon. A study in double-breasted unlined camel hair paired with wide pleated raw silk trousers. Now archived in the Metamorphoo permanent register.',
    tier: 'EDIT',
    season: 'Season 0: The Private Prototype Salon (Vaulted)',
    seasonCode: 'ARCHIVE_VAULT',
    status: 'vaulted',
    allocationNotes: 'Vaulted Record · Edition Closed · Available strictly by ATELIER Commission',
    oneRuleBroken: 'Double-breasted tailored structure cut in an ultra-soft unpadded shoulder drop.',
    heroImage:
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=85',
        caption: 'Archival Record — Lisbon courtyard morning lighting',
        type: 'full',
      },
      {
        url: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=1200&q=85',
        caption: 'Fabric Texture — 440gsm unbleached camel hair fleece',
        type: 'texture',
      },
    ],
    items: [
      {
        id: 'vic-01',
        name: 'Unpadded Camel Hair Double-Breasted Jacket',
        category: 'Jacket',
        price: 850,
        currency: 'USD',
        composition: '100% Mongolian Baby Camel Hair (440gsm)',
        tier: 'EDIT',
        origin: 'Porto / Northern Portugal Atelier',
        silhouette: 'Relaxed 6x2 double breasted with patch pockets and soft spalla camicia shoulder',
        image:
          'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=85',
        sizes: ['Vaulted Archive'],
        description: 'The foundation archetype of the Metamorphoo shoulder doctrine.',
        curationNote: 'Metamorphoo Archive Collection · Edition Closed.',
        fitGuidance: {
          cut: 'Fluid Architectural',
          modelStats: 'Archival size 50 cut',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'Vaulted edition',
        },
        provenance: {
          condition: 'Archival Master Piece',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 50, y: 35 },
      },
    ],
  },
  {
    id: 'vault-2',
    slug: 'the-solitary',
    name: 'THE SOLITARY',
    subName: 'Season 0 Archive · Look 02 (Vaulted)',
    occasion: 'Archival Study, Sea Port Twilight',
    paletteDescription: 'Deep Indigo + Unbleached Cotton Salt',
    paletteColors: ['#1C2A39', '#E8E0D5', '#C9B89A', '#14110E'],
    statementQuote: 'Solitude with unmistakable authority.',
    longThesis:
      'The raw prototype for our equatorial evening wear. Built around natural fermentation indigo dyed in Abeokuta, Nigeria and tailored in Biella.',
    tier: 'EDIT',
    season: 'Season 0: The Private Prototype Salon (Vaulted)',
    seasonCode: 'ARCHIVE_VAULT',
    status: 'vaulted',
    allocationNotes: 'Vaulted Record · Edition Closed · Available strictly by ATELIER Commission',
    oneRuleBroken: 'Deep fermented natural indigo dye on formal bespoke opera trousers.',
    heroImage:
      'https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?auto=format&fit=crop&w=1600&q=85',
    galleryImages: [
      {
        url: 'https://images.unsplash.com/photo-1534030347209-467a5b0ad3e6?auto=format&fit=crop&w=1200&q=85',
        caption: 'Archival Record — Indigo drape against ocean horizon',
        type: 'full',
      },
    ],
    items: [
      {
        id: 'sol-01',
        name: 'Natural Fermented Indigo Silk Trousers',
        category: 'Trousers',
        price: 520,
        currency: 'USD',
        composition: '60% Wild Silk, 40% Long-Staple Cotton, Natural Abeokuta Indigo Vats',
        tier: 'EDIT',
        origin: 'Abeokuta, Nigeria / Biella, Italy',
        silhouette: 'Deep double forward pleat with sweeping 26cm hem',
        image:
          'https://images.unsplash.com/photo-1479064555552-3ef4979f8908?auto=format&fit=crop&w=800&q=85',
        sizes: ['Vaulted Archive'],
        description: 'Dyed over six weeks in ancient clay fermentation pits in southwestern Nigeria.',
        curationNote: 'Metamorphoo Archive Collection · Edition Closed.',
        fitGuidance: {
          cut: 'Exaggerated Relaxed',
          modelStats: 'Archival size 48 cut',
          drapeWeight: 'Heavyweight Archival (340-420gsm)',
          recommendedSizing: 'Vaulted edition',
        },
        provenance: {
          condition: 'Archival Master Piece',
          inspectionBy: 'Ani Chisom & Metamorphoo Curatorial Bureau',
          authenticationStandard: '100% Natural Fibre Integrity · Zero Synthetic Tension',
          packaging: 'Archival Breathable Cotton Travel Garment Case + Cedar Block',
        },
        pinLocation: { x: 48, y: 65 },
      },
    ],
  },
];

export const BRAND_STORY = {
  foundingStatement:
    'METAMORPHOO is not a store. It is a wardrobe — a curated world of complete decisions, presented cinematically. We do not ask the client to assemble outfits from disparate racks; we present the complete resolution of form, texture, and proportion. Each look is already made. You say yes or no to the whole picture.',
  philosophy: 'Your dressing is as important as the room.',
  philosophyExpanded:
    'In old port cities and sovereign salons from Lagos to Lisbon to Milan, presence is never earned through shouting logos or trend-chasing. It is felt in the weight of unbleached linen, the relaxed volume of a double-pleated trouser, and the deliberate rule broken with purpose.',
  houseStructure: [
    {
      tier: 'EDIT',
      title: 'Curated External Pieces',
      description:
        'Selected across global workshops and heritage mills. Filtered relentlessly against the METAMORPHOO standard for fabric honesty, silhouette discipline, and unbranded quiet prestige.',
      status: 'Live at Launch',
    },
    {
      tier: 'ORIGINALS',
      title: 'Manufactured by METAMORPHOO',
      description:
        'Bespoke garments manufactured in limited numbered editions. Marked solely with the hairline MΦ monogram in Bone tone. Crafted from proprietary textiles developed in Portugal and Italy.',
      status: 'Phase 2 Preview',
    },
    {
      tier: 'ATELIER',
      title: 'Private Haute Commission',
      description:
        'Individual sartorial commissions tailored directly for heads of state, diplomats, and cultural arbiters. One-of-one private fittings by invitation.',
      status: 'Private Inquiries Only',
    },
  ],
  founder: {
    name: 'Ani Chisom',
    title: 'Founder & Creative Director',
    bio:
      'Architect of the METAMORPHOO aesthetic. Bridging the sartorial heritage of West African ceremonial poise with Mediterranean architectural minimalism, Ani Chisom established METAMORPHOO to liberate clients from the fatigue of micro-consumption into the clarity of complete wardrobe decisions.',
  },
  editorialManifesto: {
    rule: 'Every look is a proper noun with "The" as a prefix, always. The word itself sounds inherited — like a title, a place, a figure. Never descriptive. Never functional.',
    criteria: [
      'Single word (two at maximum — never a phrase)',
      'Sounds like it already existed before the brand — inherited, not invented',
      'Implies a character or position, not a product category',
      'Feels equally at home in Lagos, Lisbon, and Milan',
    ],
    oneRuleBrokenPrinciple:
      'Every look observes old money conventions — and breaks exactly one. Whether proportion (tailored shirt + exaggerated baggy trouser), texture (silk tux with raw stone ring), or shoes slightly unexpected, this is where the rebellious edge lives.',
  },
};
